# Generated by Django 6.1.1 on 2026-09-12 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The project this team works on. Teams are spawned by projects.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='projects.project'),
        ),
    ]
