# Generated by Django 6.1.1 on 2026-09-12 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_certificateaward_approved_by_certificateaward_status'),
        ('teams', '0003_alter_team_name_team_unique_project_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSkillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_level', models.PositiveSmallIntegerField(choices=[(1, 'Novice'), (2, 'Basic'), (3, 'Independent'), (4, 'Advanced'), (5, 'Expert')], default=3)),
                ('importance', models.CharField(choices=[('critical', 'Critical'), ('important', 'Important'), ('optional', 'Optional')], default='important', max_length=20)),
                ('people_needed', models.PositiveSmallIntegerField(blank=True, help_text='How many people need this skill at the required level.', null=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_requirements', to='skills.skill')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='teams.team')),
            ],
            options={
                'ordering': ['-importance', 'skill__name'],
                'constraints': [models.UniqueConstraint(fields=('team', 'skill'), name='unique_team_skill')],
            },
        ),
    ]
