# Generated by Django 6.1.1 on 2026-09-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_department_team_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamskillrequirement',
            name='purpose',
            field=models.CharField(choices=[('current', 'Current role'), ('promotion', 'Next position')], default='current', help_text="'Current role' gaps block today's work; 'Next position' gaps define promotion-readiness.", max_length=20),
        ),
    ]
