# Generated by Django 6.1.1 on 2026-09-12 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('planned', 'Planned'), ('completed', 'Completed')], default='active', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSkillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_level', models.PositiveSmallIntegerField(choices=[(1, 'Novice'), (2, 'Basic'), (3, 'Independent'), (4, 'Advanced'), (5, 'Expert')], default=3)),
                ('importance', models.CharField(choices=[('critical', 'Critical'), ('important', 'Important'), ('optional', 'Optional')], default='important', max_length=20)),
                ('people_needed', models.PositiveSmallIntegerField(blank=True, help_text='How many people need this skill at the required level.', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='projects.project')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_requirements', to='skills.skill')),
            ],
            options={
                'ordering': ['-importance', 'skill__name'],
                'constraints': [models.UniqueConstraint(fields=('project', 'skill'), name='unique_project_skill')],
            },
        ),
    ]
