# Generated by Django 6.1.1 on 2026-09-12 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('teams', '0005_migrate_project_requirements'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectskillrequirement',
            name='unique_project_skill',
        ),
        migrations.DeleteModel(
            name='ProjectSkillRequirement',
        ),
    ]
