# Generated by Django 6.1.1 on 2026-09-13 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadinessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='org', help_text="'org' or the department name this snapshot covers.", max_length=30)),
                ('score', models.PositiveSmallIntegerField(default=0, help_text='0–100 readiness headline metric.')),
                ('critical_skills_count', models.PositiveSmallIntegerField(default=0)),
                ('detail_json', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['scope', '-created_at'], name='insights_re_scope_a6216b_idx')],
            },
        ),
        migrations.CreateModel(
            name='StrategicInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('board', 'Board / CEO'), ('csuite', 'C-Suite'), ('department', 'Department'), ('team', 'Team')], default='department', max_length=20)),
                ('ai_draft_content', models.TextField(blank=True, help_text='AI-drafted plan. NOT used by the level below.')),
                ('approved_content', models.TextField(blank=True, help_text='Human-approved plan — the only content the next level inherits.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_initiatives', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_initiatives', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='The approved plan this initiative cascades from.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='insights.strategicinitiative')),
            ],
            options={
                'ordering': ['-level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TeamFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('feasibility', 'Feasibility gap'), ('workforce_shortfall', 'Workforce shortfall'), ('skill_shortfall', 'Skill shortfall'), ('readiness', 'Readiness problem'), ('other', 'Other')], default='readiness', max_length=30)),
                ('description', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('initiative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='insights.strategicinitiative')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
