# Generated by Django 6.1.1 on 2026-09-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expected_leave_date',
            field=models.DateField(blank=True, help_text='Leadership-estimated date this person is expected to leave.', null=True),
        ),
    ]
