# Generated by Django 6.1.1 on 2026-09-13 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_certificateaward_skill_certificateaward_level'),
        ('teams', '0006_department_team_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategory',
            name='domain',
            field=models.CharField(choices=[('technical', 'Technical'), ('business', 'Business'), ('leadership', 'Leadership')], default='technical', help_text='Top-level taxonomy domain this category belongs to.', max_length=20),
        ),
        migrations.AddField(
            model_name='skillproficiency',
            name='last_used',
            field=models.DateField(blank=True, help_text='Most recent date this skill was evaluated or actively used.', null=True),
        ),
        migrations.AddField(
            model_name='skillproficiency',
            name='validation_source',
            field=models.CharField(blank=True, help_text='How this rating was validated (e.g. self assessment, manager evaluation, peer feedback, certification, project evidence).', max_length=30),
        ),
        migrations.CreateModel(
            name='SkillFutureDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('emerging', 'Emerging'), ('growing', 'Growing'), ('stable', 'Stable'), ('declining', 'Declining')], default='emerging', max_length=20)),
                ('future_importance', models.PositiveSmallIntegerField(default=3, help_text='1–5 importance within the 5–10 year horizon.')),
                ('confidence_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='How confident we are in this projection.', max_length=20)),
                ('horizon', models.CharField(default='12–24 months', help_text='Time horizon the projection applies to.', max_length=50)),
                ('source', models.CharField(blank=True, help_text='Curated report, market data, or AI-assisted draft.', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='future_demands', to='skills.skill')),
            ],
            options={
                'ordering': ['-future_importance', 'skill__name'],
            },
        ),
        migrations.CreateModel(
            name='SkillCriticalityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_impact', models.PositiveSmallIntegerField(default=3, help_text='1–5: business impact if the skill disappears.')),
                ('strategic_relevance', models.PositiveSmallIntegerField(default=3, help_text='1–5: how aligned the skill is with the company strategy.')),
                ('time_to_replace_months', models.PositiveIntegerField(default=12, help_text='Semi-automated: how long to hire/replace externally.')),
                ('criticality_score', models.PositiveSmallIntegerField(default=0, help_text='0–100 computed score (see insights.services.criticality_formula).')),
                ('version', models.PositiveIntegerField(default=1)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criticality_assessments', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criticality_assessments', to='teams.department')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criticality_assessments', to='skills.skill')),
            ],
            options={
                'verbose_name_plural': 'criticality assessments',
                'ordering': ['-version', 'skill__name'],
                'constraints': [models.UniqueConstraint(fields=('department', 'skill', 'version'), name='unique_department_skill_version')],
            },
        ),
        migrations.CreateModel(
            name='SkillRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('related', 'Related to'), ('prerequisite', 'Prerequisite for'), ('transfers', 'Transfers to')], default='related', max_length=20)),
                ('weight', models.PositiveSmallIntegerField(default=1, help_text='0–5 affinity; used when a related skill stands in for the target.')),
                ('from_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='skills.skill')),
                ('to_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='skills.skill')),
            ],
            options={
                'ordering': ['from_skill__name', 'to_skill__name', 'kind'],
                'constraints': [models.UniqueConstraint(fields=('from_skill', 'to_skill', 'kind'), name='unique_skill_relationship')],
            },
        ),
    ]
